version: "3"

networks:
  lcmap_chipmunk:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.43.0/24

services:

  cassandra:
    image: cassandra:3.9
    ports:
    - "9042:9042"
    networks:
      - lcmap_chipmunk
    restart: always

  nginx:
    image: "nginx:latest"
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./../test/nginx/config:/etc/nginx/conf.d
      - ./../test/nginx/ssl:/etc/ssl
      - ./../test/nginx/data/:/usr/share/nginx/data
    networks:
      - lcmap_chipmunk
    restart: always

  chipmunk:
    image: "usgseros/lcmap-chipmunk:develop-1.0.0-SNAPSHOT"
    ports:
      - "5656:5656"
    environment:
      - DB_HOST=resources_cassandra_1
      - DB_KEYSPACE=chipmunk_local
      - HTTP_PORT=5656
      - Xms=4352m
      - Xmx=4352m
    networks:
      - lcmap_chipmunk
    restart: always
